### ISSUE TITLE
Great project! Let's make a README :)

### ISSUE THREAD

**Issue by colthreepv** [Textalk/prerender-ba-fs-cache#1]
Kudos to Textalk for this project, way better coded and architected than alternatives (a reason you might have coded a new one in the first place).

A README would make it really shine!

**Comment by davidlgj** [comment]
:D Thanks! I'll try do write one up this week

**Comment by davidlgj** [comment]
Hi again @mrgamer, finally there is at least a measly tiny README.md...

The big reason we coded this was to get a cache that always did the prerender work in the background so we could get more consistent speed against all the bots, with the added bonus of not crashing on a request either since if it crashed the cache is just not updated. 

We actually started out modifying the prerender-redis-cache, but after some trials it became apparent that we basically had too many pages to prerender so keeping them in memory was a poor choice, so then this project was born. 

Its a bit rough, we had to code it up quickly, there are things that could be options etc, but we do use it in production successfully.
